# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Qualification',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_type',
        ),
    ]
