# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Type',
            field=models.CharField(choices=[(b'Associate Professor', b'Associate Professor'), (b'Assistant Professor', b'Assistant Professor'), (b'Teaching Assistant', b'Teaching Assistant')], default=b'Teaching Assistant', max_length=20),
        ),
    ]
