# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0002_auto_20180212_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
