# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0003_auto_20180212_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Qualification',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='faculty_type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_code',
        ),
    ]
