# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0003_auto_20180305_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Teaching Assistant', 'Teaching Assistant')], default='Teaching Assistant', max_length=20),
        ),
    ]
