# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0004_auto_20180120_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftype', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheduler.FType'),
        ),
    ]
