# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0005_auto_20180122_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ftype',
            old_name='ftype',
            new_name='faculty_type',
        ),
    ]
