# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-28 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0006_auto_20180327_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='lecture_limit',
            field=models.IntegerField(max_length=18),
        ),
    ]
