# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0007_lecture_semester_subject_timetable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FType',
            new_name='Faculty_Type',
        ),
    ]
