# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-28 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0007_auto_20180328_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='lecture_limit',
            field=models.IntegerField(),
        ),
    ]
