# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0008_auto_20180128_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Qualification',
            field=models.CharField(default=b'MCA', max_length=300),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
