# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-04 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0017_auto_20180403_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='lab_faculty',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='sheduler.Faculty'),
        ),
    ]
