# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-04 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0022_auto_20180404_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='lab_faculty',
        ),
    ]
