# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0024_timetable_lab_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='lab_faculty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
