# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 09:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0029_remove_faculty_lecture_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='lecture_limit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
    ]
